server:
  port: 8888

spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lingo-game
    username: root
    password: Dinsdag02
  jpa:
    database: mysql
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .html
  devtools:
    restart:
      additional-paths: /resources

logging:
  level:
    org:
      springframework: ERROR